[package]
name = "erlang-memmap"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "erlmemmap"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.21.0"
memmap = "0.7.0"
