[package]
name = "winit-port"
version = "0.1.0"
authors = []
edition = "2018"

[[bin]]
name = "winit-port"
path = "src/port.rs"

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
winit = "0.21.0"
erlang-etf =  { path = "../erlang-etf" }
vulkano-win = "0.17.0"
