[package]
name = "skia"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "skia"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
skia-safe = "0.26.1"
