[package]
name = "winit"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "winit"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
winit = "0.21.0"
